[Node.P2P]
MaxPeers = 25
NoDiscovery = true
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = [
  "enode://5dd6549368cdc393e0e4f416d0b8c7bd39dee52c76744e74f6545ddb8fa446a1942d1b8b85af4efa65c01472dd74eaf6ce7ef7dac34a4d29b90e5d041b8b036a@fukuii-node1:30303",
  "enode://dc4bbd5fdf2208eca679f0934d976a1d88d96db5dc4c637f15322e741e87a9667ab93d75516f9a4c377d334c89210fb292710479d4fb9c28a83e415682062281@fukuii-node2:30303",
  "enode://463c1bc0fc25aab9aaaaed07e61474322f43826b9352e5b7004cd537873127b2778e302bf66ea207a656a333b4f3940b798c26b0acf9b03543fc6c39b79d9a6c@fukuii-node3:30303",
  "enode://9290049c2b6203640c8ff75e970cb173ce504d340fbb4dc1cb0d7718b28f6f8dbd1dc5a4e763f29099010e959cb4119d6ef52c3758bb1f193c1f171a86a46999@geth-node1:30303",
  "enode://13162d2b016bc7e356475bc3ad0293e785a029f3ed9368a7576a04a3d29d4a8fe9fba7630b046c55f85d8b2ce1b0f79425fb68413bc8661348aac7b93964a95e@geth-node3:30303"
]
TrustedNodes = [
  "enode://5dd6549368cdc393e0e4f416d0b8c7bd39dee52c76744e74f6545ddb8fa446a1942d1b8b85af4efa65c01472dd74eaf6ce7ef7dac34a4d29b90e5d041b8b036a@fukuii-node1:30303",
  "enode://dc4bbd5fdf2208eca679f0934d976a1d88d96db5dc4c637f15322e741e87a9667ab93d75516f9a4c377d334c89210fb292710479d4fb9c28a83e415682062281@fukuii-node2:30303",
  "enode://463c1bc0fc25aab9aaaaed07e61474322f43826b9352e5b7004cd537873127b2778e302bf66ea207a656a333b4f3940b798c26b0acf9b03543fc6c39b79d9a6c@fukuii-node3:30303",
  "enode://9290049c2b6203640c8ff75e970cb173ce504d340fbb4dc1cb0d7718b28f6f8dbd1dc5a4e763f29099010e959cb4119d6ef52c3758bb1f193c1f171a86a46999@geth-node1:30303",
  "enode://13162d2b016bc7e356475bc3ad0293e785a029f3ed9368a7576a04a3d29d4a8fe9fba7630b046c55f85d8b2ce1b0f79425fb68413bc8661348aac7b93964a95e@geth-node3:30303"
]
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false

[Eth.Miner]
GasFloor = 0
GasCeil = 30000000
GasPrice = 1000000000
Recommit = 2000000000
Noverify = false
NewPayloadTimeout = 2000000000
Etherbase = "0x5000000000000000000000000000000000000005"
