[Node.P2P]
MaxPeers = 25
NoDiscovery = true
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = [
  "enode://0d2bccb616d005398033ef728523227dda09f4995608bd64aa61f349461463a664024b34315c8266ac61455c1a13b2052b84abb117f126754e5bc214cf8eac15@fukuii-node1:30303",
  "enode://7c513a1f98686cfcfe879c4340aecb10c08c7abe66d653bb8295d417a8becbea130a24e6e8fa5ed60122d2296895ded4a4eacc32feb13afcc1ae56f335cf2738@fukuii-node2:30303",
  "enode://27863cba36167501f9d70f4114d23567704f7cacfed00b90e5236d7cde026558f5799c41a5bc7390267fb35d474e70aa5671bd7c099c0e84d38a3c4c5ae87803@fukuii-node3:30303",
  "enode://e9a731995f871e4ed79a46c5be719c55cd82b0c56c39f3f038b98438bcbcdcd528fe2e603e346d39a62886cdcd1d66b2262fc190464d0a14618a1ddbf014de63@geth-node1:30303",
  "enode://7259ad6a05cca15524373e9aa016517afe07265de2dbbb52f5beb11527246286ee886b79dd0d0d41d4a41f3a816d6843db1a417479b065bc513470640841926c@geth-node2:30303"
]
TrustedNodes = [
  "enode://0d2bccb616d005398033ef728523227dda09f4995608bd64aa61f349461463a664024b34315c8266ac61455c1a13b2052b84abb117f126754e5bc214cf8eac15@fukuii-node1:30303",
  "enode://7c513a1f98686cfcfe879c4340aecb10c08c7abe66d653bb8295d417a8becbea130a24e6e8fa5ed60122d2296895ded4a4eacc32feb13afcc1ae56f335cf2738@fukuii-node2:30303",
  "enode://27863cba36167501f9d70f4114d23567704f7cacfed00b90e5236d7cde026558f5799c41a5bc7390267fb35d474e70aa5671bd7c099c0e84d38a3c4c5ae87803@fukuii-node3:30303",
  "enode://e9a731995f871e4ed79a46c5be719c55cd82b0c56c39f3f038b98438bcbcdcd528fe2e603e346d39a62886cdcd1d66b2262fc190464d0a14618a1ddbf014de63@geth-node1:30303",
  "enode://7259ad6a05cca15524373e9aa016517afe07265de2dbbb52f5beb11527246286ee886b79dd0d0d41d4a41f3a816d6843db1a417479b065bc513470640841926c@geth-node2:30303"
]
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false

[Eth.Miner]
GasFloor = 0
GasCeil = 30000000
GasPrice = 1000000000
Recommit = 2000000000
Noverify = false
NewPayloadTimeout = 2000000000
Etherbase = "0x6000000000000000000000000000000000000006"
