[Node.P2P]
MaxPeers = 25
NoDiscovery = true
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = [
  "enode://cfe4c4443de8c247cadb77c19266ad64c91263a76cf7c314dbbf55bbdabfa8b0b9e8eac1a4e7eff66de997994ea70e77fbaebd5ccc59d988e789a072063af783@172.25.0.11:30303",
  "enode://ba96abcb8f1ab2731b9674e5946c0deccdb51c5eb4fe859f0a6d4878a58cd2f2aa75ff10d3f44d13f34c3ee74566a0f9c813ccc0962a543bcd05c80501f0881d@172.25.0.12:30303",
  "enode://b712a12dc793828f4c50c8bf4cc3140330d8c52b9d51bac97d5353f2dc7c93cbb1e757c88192ac03f61df2ee3f04d3bcfdd422361b91266a3a6cfe937faf726a@172.25.0.13:30303",
  "enode://b42b733f411e74ccec9a5a12fdcf72980746309cb8f0be6c62473c400d6c20438987bd0abedee450f61aca770172cc090ed83134d2fee9b5cc5cc2401d9ebf0d@172.25.0.22:30303",
  "enode://0af7f713daf50f7ebdf00e64c00fa02d2aa9b1ce646825afa814c66ddb69ee751fb7f3df8b69ffb76fe502d22afb8be8d3995708f31ebc1137355929d7814603@172.25.0.23:30303"
]
TrustedNodes = [
  "enode://cfe4c4443de8c247cadb77c19266ad64c91263a76cf7c314dbbf55bbdabfa8b0b9e8eac1a4e7eff66de997994ea70e77fbaebd5ccc59d988e789a072063af783@172.25.0.11:30303",
  "enode://ba96abcb8f1ab2731b9674e5946c0deccdb51c5eb4fe859f0a6d4878a58cd2f2aa75ff10d3f44d13f34c3ee74566a0f9c813ccc0962a543bcd05c80501f0881d@172.25.0.12:30303",
  "enode://b712a12dc793828f4c50c8bf4cc3140330d8c52b9d51bac97d5353f2dc7c93cbb1e757c88192ac03f61df2ee3f04d3bcfdd422361b91266a3a6cfe937faf726a@172.25.0.13:30303",
  "enode://b42b733f411e74ccec9a5a12fdcf72980746309cb8f0be6c62473c400d6c20438987bd0abedee450f61aca770172cc090ed83134d2fee9b5cc5cc2401d9ebf0d@172.25.0.22:30303",
  "enode://0af7f713daf50f7ebdf00e64c00fa02d2aa9b1ce646825afa814c66ddb69ee751fb7f3df8b69ffb76fe502d22afb8be8d3995708f31ebc1137355929d7814603@172.25.0.23:30303"
]
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false

[Eth.Miner]
GasFloor = 0
GasCeil = 30000000
GasPrice = 1000000000
Recommit = 2000000000
Noverify = false
NewPayloadTimeout = 2000000000
Etherbase = "0x4000000000000000000000000000000000000004"
