version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  fukuii-net:

services:

  prometheus:
    image: prom/prometheus:v2.23.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - fukuii:fukuii
    depends_on:
      - fukuii
    networks:
      - fukuii-net
    restart: always

  fukuii:
    image: fukuii:latest
    ports:
      - 8546:8546
      - 13798:13798
      - 9095:9095
    networks:
      - fukuii-net
    restart: always

  grafana:
    image: grafana/grafana:7.3.6
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - fukuii-net
    restart: always

