[Node.P2P]
StaticNodes = [
  "enode://c9717f59fcfca32928692eff3752dada02f2d14a361b358bec6b78870a7a44386012a28ef83251f63e4902830a9516e7e81b13308f695bff28b2f793dc668e3c@fukuii:9076"
]
TrustedNodes = [
  "enode://c9717f59fcfca32928692eff3752dada02f2d14a361b358bec6b78870a7a44386012a28ef83251f63e4902830a9516e7e81b13308f695bff28b2f793dc668e3c@fukuii:9076"
]
