[Node.P2P]
StaticNodes = [
  "enode://19aea906b39b0e822b5970bea0a9e12c9ee114dc11024ed39226230cd2ea928a18f005f8b8386b6911e2f71a9dc6d3d99c3a6ff5abaa6c30b01bc26c4a1c0b77@fukuii:9076"
]
TrustedNodes = [
  "enode://19aea906b39b0e822b5970bea0a9e12c9ee114dc11024ed39226230cd2ea928a18f005f8b8386b6911e2f71a9dc6d3d99c3a6ff5abaa6c30b01bc26c4a1c0b77@fukuii:9076"
]
