[Node.P2P]
StaticNodes = [
  "enode://a62595caaa2b344adc4a46425ed917fe7e584557bc09c4b969123b45f5d8b9ae23537f61fc62acd7c9937cd46fac2ab40bb968295358a385a7f3ddd86fcef975@fukuii:9076"
]
TrustedNodes = [
  "enode://a62595caaa2b344adc4a46425ed917fe7e584557bc09c4b969123b45f5d8b9ae23537f61fc62acd7c9937cd46fac2ab40bb968295358a385a7f3ddd86fcef975@fukuii:9076"
]
