[Node.P2P]
StaticNodes = [
  "enode://5299c5e91dabf834231ff1d46632a60a8812d31c24d879d86a3f695f55b02b1f35b19098b916e0c1d865ffbd9e12ba1c86b4c7162dc1e1818f80d83f46ceece2@fukuii:9076"
]
TrustedNodes = [
  "enode://5299c5e91dabf834231ff1d46632a60a8812d31c24d879d86a3f695f55b02b1f35b19098b916e0c1d865ffbd9e12ba1c86b4c7162dc1e1818f80d83f46ceece2@fukuii:9076"
]
