[Node.P2P]
StaticNodes = [
  "enode://580ed737edfc40b8e7846a56c31b3477f4ddbc183487ebc858f390e5f1ac7ac70f119d26ae268880162f567d1e114c5ebcd94d8cfe155793041f7f4150274199@fukuii:9076"
]
TrustedNodes = [
  "enode://580ed737edfc40b8e7846a56c31b3477f4ddbc183487ebc858f390e5f1ac7ac70f119d26ae268880162f567d1e114c5ebcd94d8cfe155793041f7f4150274199@fukuii:9076"
]
