[Node.P2P]
StaticNodes = [
  "enode://f468cbb0c03e2730fe733085aab0bb25657c2a99d323703a08848d42f1aa1cd46dcf921eb24fa4542dd60f539415103681661ae59cf231cb5c0464597a4799f3@fukuii:9076"
]
TrustedNodes = [
  "enode://f468cbb0c03e2730fe733085aab0bb25657c2a99d323703a08848d42f1aa1cd46dcf921eb24fa4542dd60f539415103681661ae59cf231cb5c0464597a4799f3@fukuii:9076"
]
