[Node.P2P]
StaticNodes = [
  "enode://d85e11064b38ab7769196b7d712eaec285c660ee4a9440a7147edec42a05f6e39b10663eaf543f6026bf3c24bd1e0e62d0b22f08472aeeaee668f30eb84f9d97@fukuii:9076"
]
TrustedNodes = [
  "enode://d85e11064b38ab7769196b7d712eaec285c660ee4a9440a7147edec42a05f6e39b10663eaf543f6026bf3c24bd1e0e62d0b22f08472aeeaee668f30eb84f9d97@fukuii:9076"
]
