[Node.P2P]
StaticNodes = [
  "enode://2cdb996b3f859245539277455b0f90217cf5968250b6b8437280569cf0b1f67d31289d9547b4b4976f84c7531fec146a0ec9692476be896ccc8867b72856dc1c@fukuii:9076"
]
TrustedNodes = [
  "enode://2cdb996b3f859245539277455b0f90217cf5968250b6b8437280569cf0b1f67d31289d9547b4b4976f84c7531fec146a0ec9692476be896ccc8867b72856dc1c@fukuii:9076"
]
