[Node.P2P]
StaticNodes = [
  "enode://ceea58f0fd4987bbf5f428593e8c0c9e709983b11507a95cedec2a1d64b350b0787884c48ca8f70e57186001327b5207033f7c4ed32f4d9e7f1420b4abc83dce@fukuii:9076"
]
TrustedNodes = [
  "enode://ceea58f0fd4987bbf5f428593e8c0c9e709983b11507a95cedec2a1d64b350b0787884c48ca8f70e57186001327b5207033f7c4ed32f4d9e7f1420b4abc83dce@fukuii:9076"
]
