[Node.P2P]
StaticNodes = [
  "enode://64f55113c8a5a01a5c2395853591ea3602f364fe1ec74da41cc7ed46e6cb6533be44b530932f37b3df637733f5e81fb8a02a2ac2e4c274f751f48686d430e994@fukuii:9076"
]
TrustedNodes = [
  "enode://64f55113c8a5a01a5c2395853591ea3602f364fe1ec74da41cc7ed46e6cb6533be44b530932f37b3df637733f5e81fb8a02a2ac2e4c274f751f48686d430e994@fukuii:9076"
]
