[Node.P2P]
StaticNodes = [
  "enode://96591d3604d2af9aa503592f183f0244ff4eb28dd95ad01849b4cab5b729216b4c9e4160701c8e03df74e3069b8b1ca6d394e332c109d3e463267ce05c7126a3@fukuii:9076"
]
TrustedNodes = [
  "enode://96591d3604d2af9aa503592f183f0244ff4eb28dd95ad01849b4cab5b729216b4c9e4160701c8e03df74e3069b8b1ca6d394e332c109d3e463267ce05c7126a3@fukuii:9076"
]
